site_name: Intro to GIS Survival Guide
nav:
    - Home: index.md
    - Getting Started: getting_started.md
    - Common Errors: common_errors.md
theme: 
    name: material
    favicon: img/favicon.png
    logo: img/favicon.png